/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: '43_Sending_Data_via_Bluetooth_Serial_Port_Water_Level_Sensor' 
 * Target:  '43_Sending_Data_via_Bluetooth_Serial_Port_Water_Level_Sensor' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"



#endif /* RTE_COMPONENTS_H */
